spring:
  application:
    name: EMPLOYEE-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://192.186.2.174:8761/eureka/
  instance:
    hostname: 192.186.2.174
